### PR TITLE
fix syntax to complain standars

### PR DESCRIPTION
**Pull request by iyesin**

### CODE REVIEW

**Comment by Inviz** [comment]
Hello! So excited to see a pull request! 

I want to accept it, but you've closed it. Can I reopen? Sorry for crude C.

May I ask how do you use this fork (what  features)?  Hope you saw the crazy stuff it can do. 

https://github.com/konstruxi/skema/blob/master/conf/app/resource.conf

**Comment by Inviz** [comment]
Added you as collaborator, just in case!

**Comment by iyesin** [comment]
Hello.

I'm sorry. This was accidental merge request.
It wasn't tested in real build environment.
Nowadays I'm testing new version (which can compile with redhat default -Werror setting).

**Comment by Inviz** [comment]
Don't be sorry, it was nice anyway. Thanks for checking this out.

Admittedly, I didn't try newer version of nginx (or ngx_postgres upstream). I'd like to do some more things using this project in a month or two. I'd be happy to merge in your changes as-is if you'll want it.

**Pull request closed without merging**
